run:
  timeout: 5m
  skip-dirs:
    - proto

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocyclo
    - dupl
    - goconst

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude-dirs:
    - proto
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_grpc\\.pb\\.go$"
  exclude-rules:
    - path: services/.*/cmd/server/main.go
      linters:
        - errcheck
      text: "Error return value of.*Close.*is not checked"
    - path: services/.*/cmd/server/main.go
      linters:
        - errcheck
      text: "Error return value of.*Sync.*is not checked"
    - path: services/.*/cmd/server/main.go
      linters:
        - errcheck
      text: "Error return value of.*Write.*is not checked"
