global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'coldy-prod'
    env: 'production'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - '/etc/prometheus/rules/*.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

  - job_name: 'users-service'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - coldy-prod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: coldy-users
        action: keep

  - job_name: 'catalog-service'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - coldy-prod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: coldy-catalog
        action: keep

  - job_name: 'orders-service'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - coldy-prod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: coldy-orders
        action: keep

  - job_name: 'payments-service'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - coldy-prod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: coldy-payments
        action: keep

  - job_name: 'inventory-service'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - coldy-prod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: coldy-inventory
        action: keep

