// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/payments/v1/payments.proto

package paymentsv1

import (
	v1 "github.com/mumumio1/coldy/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_PROCESSING  PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_SUCCEEDED   PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 4
	PaymentStatus_PAYMENT_STATUS_CANCELED   PaymentStatus = 5
	PaymentStatus_PAYMENT_STATUS_REFUNDED    PaymentStatus = 6
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_PROCESSING",
		3: "PAYMENT_STATUS_SUCCEEDED",
		4: "PAYMENT_STATUS_FAILED",
		5: "PAYMENT_STATUS_CANCELED",
		6: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_PROCESSING":  2,
		"PAYMENT_STATUS_SUCCEEDED":   3,
		"PAYMENT_STATUS_FAILED":      4,
		"PAYMENT_STATUS_CANCELED":   5,
		"PAYMENT_STATUS_REFUNDED":    6,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_payments_v1_payments_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_proto_payments_v1_payments_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_payments_v1_payments_proto_rawDescGZIP(), []int{0}
}

type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED   PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_CARD          PaymentMethod = 1
	PaymentMethod_PAYMENT_METHOD_PAYPAL        PaymentMethod = 2
	PaymentMethod_PAYMENT_METHOD_BANK_TRANSFER PaymentMethod = 3
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "PAYMENT_METHOD_CARD",
		2: "PAYMENT_METHOD_PAYPAL",
		3: "PAYMENT_METHOD_BANK_TRANSFER",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED":   0,
		"PAYMENT_METHOD_CARD":          1,
		"PAYMENT_METHOD_PAYPAL":        2,
		"PAYMENT_METHOD_BANK_TRANSFER": 3,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_payments_v1_payments_proto_enumTypes[1].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_proto_payments_v1_payments_proto_enumTypes[1]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_proto_payments_v1_payments_proto_rawDescGZIP(), []int{1}
}

type Payment struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId               string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId                string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount                *v1.Money              `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status                PaymentStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=payments.v1.PaymentStatus" json:"status,omitempty"`
	Method                PaymentMethod          `protobuf:"varint,6,opt,name=method,proto3,enum=payments.v1.PaymentMethod" json:"method,omitempty"`
	ProviderTransactionId string                 `protobuf:"bytes,7,opt,name=provider_transaction_id,json=providerTransactionId,proto3" json:"provider_transaction_id,omitempty"`
	ErrorMessage          string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_proto_payments_v1_payments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_v1_payments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_proto_payments_v1_payments_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Payment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Payment) GetAmount() *v1.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Payment) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Payment) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *Payment) GetProviderTransactionId() string {
	if x != nil {
		return x.ProviderTransactionId
	}
	return ""
}

func (x *Payment) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Payment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreatePaymentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Metadata       *v1.RequestMetadata    `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	OrderId        string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId         string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount         *v1.Money              `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Method         PaymentMethod          `protobuf:"varint,6,opt,name=method,proto3,enum=payments.v1.PaymentMethod" json:"method,omitempty"`
	PaymentDetails map[string]string      `protobuf:"bytes,7,rep,name=payment_details,json=paymentDetails,proto3" json:"payment_details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Card number, etc.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_proto_payments_v1_payments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_v1_payments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payments_v1_payments_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreatePaymentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreatePaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreatePaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmount() *v1.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreatePaymentRequest) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *CreatePaymentRequest) GetPaymentDetails() map[string]string {
	if x != nil {
		return x.PaymentDetails
	}
	return nil
}

type CreatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	FromCache     bool                   `protobuf:"varint,2,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_proto_payments_v1_payments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_v1_payments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payments_v1_payments_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *CreatePaymentResponse) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.RequestMetadata    `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_proto_payments_v1_payments_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_v1_payments_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payments_v1_payments_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type GetPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentResponse) Reset() {
	*x = GetPaymentResponse{}
	mi := &file_proto_payments_v1_payments_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentResponse) ProtoMessage() {}

func (x *GetPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_v1_payments_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payments_v1_payments_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type ConfirmPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.RequestMetadata    `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentRequest) Reset() {
	*x = ConfirmPaymentRequest{}
	mi := &file_proto_payments_v1_payments_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentRequest) ProtoMessage() {}

func (x *ConfirmPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_v1_payments_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payments_v1_payments_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmPaymentRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ConfirmPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type ConfirmPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentResponse) Reset() {
	*x = ConfirmPaymentResponse{}
	mi := &file_proto_payments_v1_payments_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentResponse) ProtoMessage() {}

func (x *ConfirmPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_v1_payments_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentResponse.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payments_v1_payments_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmPaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type CancelPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.RequestMetadata    `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPaymentRequest) Reset() {
	*x = CancelPaymentRequest{}
	mi := &file_proto_payments_v1_payments_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPaymentRequest) ProtoMessage() {}

func (x *CancelPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_v1_payments_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPaymentRequest.ProtoReflect.Descriptor instead.
func (*CancelPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payments_v1_payments_proto_rawDescGZIP(), []int{7}
}

func (x *CancelPaymentRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CancelPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CancelPaymentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPaymentResponse) Reset() {
	*x = CancelPaymentResponse{}
	mi := &file_proto_payments_v1_payments_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPaymentResponse) ProtoMessage() {}

func (x *CancelPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_v1_payments_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPaymentResponse.ProtoReflect.Descriptor instead.
func (*CancelPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payments_v1_payments_proto_rawDescGZIP(), []int{8}
}

func (x *CancelPaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type RefundPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.RequestMetadata    `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount        *v1.Money              `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"` // Partial or full refund
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentRequest) Reset() {
	*x = RefundPaymentRequest{}
	mi := &file_proto_payments_v1_payments_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentRequest) ProtoMessage() {}

func (x *RefundPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_v1_payments_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentRequest.ProtoReflect.Descriptor instead.
func (*RefundPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payments_v1_payments_proto_rawDescGZIP(), []int{9}
}

func (x *RefundPaymentRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RefundPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *RefundPaymentRequest) GetAmount() *v1.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *RefundPaymentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RefundPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	RefundId      string                 `protobuf:"bytes,2,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentResponse) Reset() {
	*x = RefundPaymentResponse{}
	mi := &file_proto_payments_v1_payments_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentResponse) ProtoMessage() {}

func (x *RefundPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_v1_payments_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentResponse.ProtoReflect.Descriptor instead.
func (*RefundPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payments_v1_payments_proto_rawDescGZIP(), []int{10}
}

func (x *RefundPaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *RefundPaymentResponse) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

var File_proto_payments_v1_payments_proto protoreflect.FileDescriptor

const file_proto_payments_v1_payments_proto_rawDesc = "" +
	"\n" +
	" proto/payments/v1/payments.proto\x12\vpayments.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cproto/common/v1/common.proto\"\xb2\x03\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12(\n" +
	"\x06amount\x18\x04 \x01(\v2\x10.common.v1.MoneyR\x06amount\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1a.payments.v1.PaymentStatusR\x06status\x122\n" +
	"\x06method\x18\x06 \x01(\x0e2\x1a.payments.v1.PaymentMethodR\x06method\x126\n" +
	"\x17provider_transaction_id\x18\a \x01(\tR\x15providerTransactionId\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xac\x03\n" +
	"\x14CreatePaymentRequest\x126\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1a.common.v1.RequestMetadataR\bmetadata\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12(\n" +
	"\x06amount\x18\x05 \x01(\v2\x10.common.v1.MoneyR\x06amount\x122\n" +
	"\x06method\x18\x06 \x01(\x0e2\x1a.payments.v1.PaymentMethodR\x06method\x12^\n" +
	"\x0fpayment_details\x18\a \x03(\v25.payments.v1.CreatePaymentRequest.PaymentDetailsEntryR\x0epaymentDetails\x1aA\n" +
	"\x13PaymentDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\x15CreatePaymentResponse\x12.\n" +
	"\apayment\x18\x01 \x01(\v2\x14.payments.v1.PaymentR\apayment\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x02 \x01(\bR\tfromCache\"j\n" +
	"\x11GetPaymentRequest\x126\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1a.common.v1.RequestMetadataR\bmetadata\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\"D\n" +
	"\x12GetPaymentResponse\x12.\n" +
	"\apayment\x18\x01 \x01(\v2\x14.payments.v1.PaymentR\apayment\"n\n" +
	"\x15ConfirmPaymentRequest\x126\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1a.common.v1.RequestMetadataR\bmetadata\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\"H\n" +
	"\x16ConfirmPaymentResponse\x12.\n" +
	"\apayment\x18\x01 \x01(\v2\x14.payments.v1.PaymentR\apayment\"\x85\x01\n" +
	"\x14CancelPaymentRequest\x126\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1a.common.v1.RequestMetadataR\bmetadata\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"G\n" +
	"\x15CancelPaymentResponse\x12.\n" +
	"\apayment\x18\x01 \x01(\v2\x14.payments.v1.PaymentR\apayment\"\xaf\x01\n" +
	"\x14RefundPaymentRequest\x126\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1a.common.v1.RequestMetadataR\bmetadata\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12(\n" +
	"\x06amount\x18\x03 \x01(\v2\x10.common.v1.MoneyR\x06amount\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"d\n" +
	"\x15RefundPaymentResponse\x12.\n" +
	"\apayment\x18\x01 \x01(\v2\x14.payments.v1.PaymentR\apayment\x12\x1b\n" +
	"\trefund_id\x18\x02 \x01(\tR\brefundId*\xde\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19PAYMENT_STATUS_PROCESSING\x10\x02\x12\x1c\n" +
	"\x18PAYMENT_STATUS_SUCCEEDED\x10\x03\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x04\x12\x1c\n" +
	"\x18PAYMENT_STATUS_CANCELED\x10\x05\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x06*\x85\x01\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PAYMENT_METHOD_CARD\x10\x01\x12\x19\n" +
	"\x15PAYMENT_METHOD_PAYPAL\x10\x02\x12 \n" +
	"\x1cPAYMENT_METHOD_BANK_TRANSFER\x10\x032\xc2\x03\n" +
	"\x0ePaymentService\x12V\n" +
	"\rCreatePayment\x12!.payments.v1.CreatePaymentRequest\x1a\".payments.v1.CreatePaymentResponse\x12M\n" +
	"\n" +
	"GetPayment\x12\x1e.payments.v1.GetPaymentRequest\x1a\x1f.payments.v1.GetPaymentResponse\x12Y\n" +
	"\x0eConfirmPayment\x12\".payments.v1.ConfirmPaymentRequest\x1a#.payments.v1.ConfirmPaymentResponse\x12V\n" +
	"\rCancelPayment\x12!.payments.v1.CancelPaymentRequest\x1a\".payments.v1.CancelPaymentResponse\x12V\n" +
	"\rRefundPayment\x12!.payments.v1.RefundPaymentRequest\x1a\".payments.v1.RefundPaymentResponseB8Z6github.com/mumumio1/coldy/proto/payments/v1;paymentsv1b\x06proto3"

var (
	file_proto_payments_v1_payments_proto_rawDescOnce sync.Once
	file_proto_payments_v1_payments_proto_rawDescData []byte
)

func file_proto_payments_v1_payments_proto_rawDescGZIP() []byte {
	file_proto_payments_v1_payments_proto_rawDescOnce.Do(func() {
		file_proto_payments_v1_payments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payments_v1_payments_proto_rawDesc), len(file_proto_payments_v1_payments_proto_rawDesc)))
	})
	return file_proto_payments_v1_payments_proto_rawDescData
}

var file_proto_payments_v1_payments_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_payments_v1_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_payments_v1_payments_proto_goTypes = []any{
	(PaymentStatus)(0),             // 0: payments.v1.PaymentStatus
	(PaymentMethod)(0),             // 1: payments.v1.PaymentMethod
	(*Payment)(nil),                // 2: payments.v1.Payment
	(*CreatePaymentRequest)(nil),   // 3: payments.v1.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),  // 4: payments.v1.CreatePaymentResponse
	(*GetPaymentRequest)(nil),      // 5: payments.v1.GetPaymentRequest
	(*GetPaymentResponse)(nil),     // 6: payments.v1.GetPaymentResponse
	(*ConfirmPaymentRequest)(nil),  // 7: payments.v1.ConfirmPaymentRequest
	(*ConfirmPaymentResponse)(nil), // 8: payments.v1.ConfirmPaymentResponse
	(*CancelPaymentRequest)(nil),   // 9: payments.v1.CancelPaymentRequest
	(*CancelPaymentResponse)(nil),  // 10: payments.v1.CancelPaymentResponse
	(*RefundPaymentRequest)(nil),   // 11: payments.v1.RefundPaymentRequest
	(*RefundPaymentResponse)(nil),  // 12: payments.v1.RefundPaymentResponse
	nil,                            // 13: payments.v1.CreatePaymentRequest.PaymentDetailsEntry
	(*v1.Money)(nil),               // 14: common.v1.Money
	(*timestamppb.Timestamp)(nil),  // 15: google.protobuf.Timestamp
	(*v1.RequestMetadata)(nil),     // 16: common.v1.RequestMetadata
}
var file_proto_payments_v1_payments_proto_depIdxs = []int32{
	14, // 0: payments.v1.Payment.amount:type_name -> common.v1.Money
	0,  // 1: payments.v1.Payment.status:type_name -> payments.v1.PaymentStatus
	1,  // 2: payments.v1.Payment.method:type_name -> payments.v1.PaymentMethod
	15, // 3: payments.v1.Payment.created_at:type_name -> google.protobuf.Timestamp
	15, // 4: payments.v1.Payment.updated_at:type_name -> google.protobuf.Timestamp
	16, // 5: payments.v1.CreatePaymentRequest.metadata:type_name -> common.v1.RequestMetadata
	14, // 6: payments.v1.CreatePaymentRequest.amount:type_name -> common.v1.Money
	1,  // 7: payments.v1.CreatePaymentRequest.method:type_name -> payments.v1.PaymentMethod
	13, // 8: payments.v1.CreatePaymentRequest.payment_details:type_name -> payments.v1.CreatePaymentRequest.PaymentDetailsEntry
	2,  // 9: payments.v1.CreatePaymentResponse.payment:type_name -> payments.v1.Payment
	16, // 10: payments.v1.GetPaymentRequest.metadata:type_name -> common.v1.RequestMetadata
	2,  // 11: payments.v1.GetPaymentResponse.payment:type_name -> payments.v1.Payment
	16, // 12: payments.v1.ConfirmPaymentRequest.metadata:type_name -> common.v1.RequestMetadata
	2,  // 13: payments.v1.ConfirmPaymentResponse.payment:type_name -> payments.v1.Payment
	16, // 14: payments.v1.CancelPaymentRequest.metadata:type_name -> common.v1.RequestMetadata
	2,  // 15: payments.v1.CancelPaymentResponse.payment:type_name -> payments.v1.Payment
	16, // 16: payments.v1.RefundPaymentRequest.metadata:type_name -> common.v1.RequestMetadata
	14, // 17: payments.v1.RefundPaymentRequest.amount:type_name -> common.v1.Money
	2,  // 18: payments.v1.RefundPaymentResponse.payment:type_name -> payments.v1.Payment
	3,  // 19: payments.v1.PaymentService.CreatePayment:input_type -> payments.v1.CreatePaymentRequest
	5,  // 20: payments.v1.PaymentService.GetPayment:input_type -> payments.v1.GetPaymentRequest
	7,  // 21: payments.v1.PaymentService.ConfirmPayment:input_type -> payments.v1.ConfirmPaymentRequest
	9,  // 22: payments.v1.PaymentService.CancelPayment:input_type -> payments.v1.CancelPaymentRequest
	11, // 23: payments.v1.PaymentService.RefundPayment:input_type -> payments.v1.RefundPaymentRequest
	4,  // 24: payments.v1.PaymentService.CreatePayment:output_type -> payments.v1.CreatePaymentResponse
	6,  // 25: payments.v1.PaymentService.GetPayment:output_type -> payments.v1.GetPaymentResponse
	8,  // 26: payments.v1.PaymentService.ConfirmPayment:output_type -> payments.v1.ConfirmPaymentResponse
	10, // 27: payments.v1.PaymentService.CancelPayment:output_type -> payments.v1.CancelPaymentResponse
	12, // 28: payments.v1.PaymentService.RefundPayment:output_type -> payments.v1.RefundPaymentResponse
	24, // [24:29] is the sub-list for method output_type
	19, // [19:24] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_payments_v1_payments_proto_init() }
func file_proto_payments_v1_payments_proto_init() {
	if File_proto_payments_v1_payments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payments_v1_payments_proto_rawDesc), len(file_proto_payments_v1_payments_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payments_v1_payments_proto_goTypes,
		DependencyIndexes: file_proto_payments_v1_payments_proto_depIdxs,
		EnumInfos:         file_proto_payments_v1_payments_proto_enumTypes,
		MessageInfos:      file_proto_payments_v1_payments_proto_msgTypes,
	}.Build()
	File_proto_payments_v1_payments_proto = out.File
	file_proto_payments_v1_payments_proto_goTypes = nil
	file_proto_payments_v1_payments_proto_depIdxs = nil
}
